### ISSUE TITLE
Unable to set up at all

### ISSUE THREAD

**Issue by bkr1969** [fuatakgun/eufy_security#1056]
Please check existing (open or closed) issues before creating a new one. (https://github.com/fuatakgun/eufy_security/issues?q=is%3Aissue+)

If this is not an issue, you can use `Discussions` (https://github.com/fuatakgun/eufy_security/discussions) section.

**Describe the bug**

**To reproduce**

**Expected behavior**

I expect to be able to follow the instructions for set up and have my camera integrated.

**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
- Home Assistant Installation Type (OS - Supvervised - Core): OS
- Home Assistant Core Version: 2023.12.4
- Eufy Security Add-on Version: v8.0.0
- Eufy Security Integration Version:

Hardware Information;
- Camera Model: Eufy s330

- Live Streaming Protocol (RTSP/P2P): RTSP

- Debug Logs from Home Assistant (https://github.com/fuatakgun/eufy_security/discussions/624) - Without this, I will automatically resolve this issue
  

- Logs from Eufy Security Add-on (either from Add-ons page of Home Assistant or Docker output):

- Would you share your device with me in case further debugging required? (Yes/No):

**Additional context**

Hitting reconfigure gives:
```
Error
Config flow could not be loaded: {"message":"Invalid flow specified"}

**Comment by bkr1969** [comment]
<img width="1024" alt="Screen Shot 2023-12-30 at 12 36 21" src="https://github.com/fuatakgun/eufy_security/assets/42385989/b504c490-df34-485c-b276-78c96aa9770f">

**Comment by 51av0sh** [comment]
@bkr1969 How did you solve this? I have the same problem

**Comment by bkr1969** [comment]
Make sure you have the correct username (email) and password in the add-on configuration.  Restart HA and reconfigure using the Captcha that comes up (if I remember correctly) then when you try to configure the actual device, you should get a verification code emailed to you.  Enter that number in the spot where you previously entered the Captcha and it should be good.  I kept having to reset my password in the app so my initial problem was that it wasn't correct in the add-on anymore. Once I fixed that and re-started the add-on, I got the verification email when configuring. I think the documentation leaves a little detail out as I know it mentions the Captcha but I don't remember anything about an additional email verification code.

**Comment by 51av0sh** [comment]
Interesting. Thanks for the feedback. Unfortunately that's not my issue. Credentials are perfectly fine and everything works (all entities are present and available) except I'm unable to configure the integration at all. I've already removed the integration completely and readded after reboots with the same result.

**Comment by 51av0sh** [comment]
I just realized my error is actually different. I get:

"Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble"

**Comment by bkr1969** [comment]
That’s what I was getting. If you get that when hitting reconfigure, restart HA. Then go back and hit reconfigure again. You will either get the Captcha or a blank space to enter your verification code.

**Comment by 51av0sh** [comment]
You might be right since I never get a captcha at all but I just tried your suggestion and I'm still getting the same error and no captcha. I just added a new camera today and that one is not showing up although my old one is.
