### ISSUE TITLE
ERROR Status return code not 200

### ISSUE THREAD

**Issue by SmartM-ui** [fuatakgun/eufy_security#128]
Hi @fuatakgun ,
today I tried to update Eufy_Security HACS and ADDON, but I have error 200. 
I had to go back to addon (0.3.3.) to be able to continue using Eufy Addon

<img width="841" alt="Schermata 2021-11-22 alle 10 58 38" src="https://user-images.githubusercontent.com/63554131/142841735-52e3a236-95ed-44fa-ad76-6a146d28abb6.png">

**Comment by fuatakgun** [comment]
was fixed here, get new version of add-on
https://github.com/bropat/eufy-security-ws/issues/46

**Comment by capandcamera** [comment]
Getting the same error on add-on version 0.5.3

2021-11-22 12:18:24.059  ERROR Status return code not 200 
{
  status: 204,
  statusText: 'No Content'
}
2021-11-22 12:18:24.663  ERROR Status return code not 200 
{
  status: 204,
  statusText: 'No Content'
}
2021-11-22 12:18:25.986  ERROR Status return code not 200 
{
  status: 204,
  statusText: 'No Content'
}
2021-11-22 12:18:26.568  ERROR Status return code not 200 
{
  status: 204,
  statusText: 'No Content'
}

**Comment by fuatakgun** [comment]
new version is 0.5.5, update it

**Comment by capandcamera** [comment]
Thank you @fuatakgun , I had to manually reload the add ons for the update to appear, all updated now and this error so far has not appeared.

Thanks again for all the hard work to get this integration running.

**Comment by SmartM-ui** [comment]
> Thank you @fuatakgun , I had to manually reload the add ons for the update to appear, all updated now and this error so far has not appeared.
> 
> Thanks again for all the hard work to get this integration running.

Hi,
How did you go about manually reloading the update to appear? Also I still see 0.5.3

**Comment by capandcamera** [comment]
@SmartM-ui when you're in Supervisor, go to 'Add-on store' click the 3 dots and click 'Reload'. 
Once you do this, click back on the Eufy Security WS Addon, and it should appear with an update available.

**Comment by SmartM-ui** [comment]
> @SmartM-ui when you're in Supervisor, go to 'Add-on store' click the 3 dots and click 'Reload'. Once you do this, click back on the Eufy Security WS Addon, and it should appear with an update available.

Thanks!

**Comment by SmartM-ui** [comment]
> new version is 0.5.5, update it

OK
With the new version 0.5.5 the problem is solved
